<template>
  <div class="markdown">
    <section>
      <h1>General Disclaimer</h1>
      <p>0xcert d.o.o. (“0xcert”) reserves the right to change, modify, add or remove portions of this document at any time for any reason and publish it on its website.</p>
      <p>This document or any other document, produced and signed by 0xcert, does not constitute an offer or solicitation to sell securities. Because tokens are not securities, 0xcert is not monitored by any securities regulator and the terms of sale have not been approved by any such regulator none of the information or analyses presented are intended to form the basis for any investment decision, and no specific recommendations are intended, and 0xcert services and the website are not, do not offer and shall not be construed as investment or investment advice or financial products. This document does not constitute investment advice or counsel or solicitation for investment in any security and shall not be construed in that way. This document does not constitute or form part of, and should not be construed as, any offer for sale or subscription of, or any invitation to offer to buy or subscribe for, any securities. No statements made herein shall be interpreted as forwarding looking statements regarding future token value. This document is of informative and not binding nature and its purpose is to present 0xcert project and functionality.</p>
      <p>0xcert tokens do not present any shareholders right in 0xcert, namely the tokens do not present shares in 0xcert, and holder of any cryptographic tokens, issued by 0xcert is not entitled to any form of profit, dividend or other revenue right, or voting right in the shareholders’ matters. 0xcert token does not present a monetary claim against 0xcert and does not generate any form of passive income right.</p>
      <p>To the extent permitted by law, 0xcert expressly disclaims any and all responsibility and liability for any direct or consequential loss, pure financial loss, loss of profits or damage of any kind whatsoever arising directly or indirectly from use of the tokens and 0xcert platform contrary to the terms set out therein.</p>
    </section>
  </div>
</template>
